[build]
  command = "npm run build"
  publish = "./dist"

[dev]
  command = ""
  publish = "./dist"


# Do this instead of looking for a shortlink redirect 
# so we can serve local images 
[[redirects]]
  from = "/image/*"
  to = "/image/:splat"
  status = 200


# Catch-all for any unfound short codes
[[redirects]]
  from = "*"
  to = "https://www.hawksworx.com/blog/find-that-at/"
  status = 302

